// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv9HqaYmnDEO3MZS2KdOXgdQnV3gIuDhE',
    appId: '1:920707975202:android:910764ba833004bb26a27b',
    messagingSenderId: '920707975202',
    projectId: 'dark-tales-e67d1',
    databaseURL: 'https://dark-tales-e67d1-default-rtdb.firebaseio.com',
    storageBucket: 'dark-tales-e67d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrGbsSYHaVNXwPBmcYP-rWobqsaOrcYQA',
    appId: '1:920707975202:ios:65cc30530eaa908426a27b',
    messagingSenderId: '920707975202',
    projectId: 'dark-tales-e67d1',
    databaseURL: 'https://dark-tales-e67d1-default-rtdb.firebaseio.com',
    storageBucket: 'dark-tales-e67d1.firebasestorage.app',
    iosBundleId: 'com.darktales.app.darktales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrGbsSYHaVNXwPBmcYP-rWobqsaOrcYQA',
    appId: '1:920707975202:ios:65cc30530eaa908426a27b',
    messagingSenderId: '920707975202',
    projectId: 'dark-tales-e67d1',
    databaseURL: 'https://dark-tales-e67d1-default-rtdb.firebaseio.com',
    storageBucket: 'dark-tales-e67d1.firebasestorage.app',
    iosBundleId: 'com.darktales.app.darktales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwan_wWD2VbkQ0cqIiDJawNjnKaBK9xdg',
    appId: '1:920707975202:web:a2f6db630bfe41f626a27b',
    messagingSenderId: '920707975202',
    projectId: 'dark-tales-e67d1',
    authDomain: 'dark-tales-e67d1.firebaseapp.com',
    databaseURL: 'https://dark-tales-e67d1-default-rtdb.firebaseio.com',
    storageBucket: 'dark-tales-e67d1.firebasestorage.app',
    measurementId: 'G-CS9JZLFNDD',
  );

}